In [4]:
import pandas as pd
import numpy as np

In [ ]:
mydata = pd.read_csv("uncleaned.csv")

In [34]:
mydata[:5] # Returns first 5 records

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [41]:
mydata.loc[8] # To get a slice of dataset or a single record at the given index

Index                    8
Age                   35.0
Salary           $44k-$99k
Rating                 5.4
Location       New York,Ny
Established             -1
Easy Apply              -1
Name: 8, dtype: object

In [48]:
len(mydata)

29

In [ ]:
mydata.describe() # To describe numerical columns of the dataset

           Index        Age     Rating  Established
count  29.000000  22.000000  28.000000    29.000000
mean   14.000000  39.045455   3.528571  1638.620690
std     8.514693  16.134781   2.825133   762.079599
min     0.000000  13.000000  -1.000000    -1.000000
25%     7.000000  25.000000   1.050000  1935.000000
50%    14.000000  39.500000   4.200000  1984.000000
75%    21.000000  50.000000   5.400000  1999.000000
max    28.000000  66.000000   7.800000  2020.000000

In [ ]:
mydata[mydata.Age.isnull()] # Returns all the records with Age as null value. This works by passing in the True/False dataset of Age column.

    Index  Age     Salary  Rating       Location  Established Easy Apply
2       2  NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
12     12  NaN  $44k-$99k     0.0       India,In         1999         -1
17     17  NaN  $44k-$99k     5.3    New York,Ny         1943       TRUE
20     20  NaN  $44k-$99k     5.7    New York,Ny         1944       TRUE
23     23  NaN  $44k-$99k     2.4    New York,Ny         1999       TRUE
26     26  NaN  $55k-$66k     NaN       India,In         1934       TRUE
28     28  NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [54]:
mydata.dtypes

Index            int64
Age            float64
Salary             str
Rating         float64
Location           str
Established      int64
Easy Apply         str
dtype: object

In [55]:
print(mydata.Location[0])

India,In